# Generated by Django 4.1.3 on 2022-11-08 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('paid', models.BooleanField()),
                ('amount', models.IntegerField()),
                ('phone', models.CharField(max_length=50)),
                ('pay_code', models.CharField(max_length=100)),
                ('shop_code', models.CharField(max_length=100)),
                ('payment_date', models.DateTimeField(auto_now=True)),
                ('admin_update', models.DateTimeField(auto_now=True)),
                ('admin_note', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
