# Generated by Django 4.1.2 on 2022-10-18 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_r', models.CharField(max_length=50)),
                ('img_r', models.ImageField(default='product.jpg', upload_to='Product')),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('max_quantity', models.IntegerField()),
                ('min_quantity', models.IntegerField()),
                ('size', models.IntegerField()),
                ('display', models.BooleanField()),
                ('shoes', models.BooleanField()),
                ('bags', models.BooleanField()),
                ('perfume', models.BooleanField()),
                ('cloth', models.BooleanField()),
                ('uploaded', models.DateField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.category')),
            ],
        ),
    ]
